language: node_js

node_js:
  - "4"

script:
  - npm run lint
  - npm test

after_success:
  - npm install coveralls lcov-result-merger
  - $(npm bin)/lcov-result-merger './coverage/*/lcov.info' | $(npm bin)/coveralls
